---

- name: Main | Install elastic deb repository
  apt_repository:
    repo: "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main"
    state: present
  become: true

- name: Main | Update apt repo and cache
  apt:
    update_cache: yes

- name: Main | Upgrade all packages
  apt:
    upgrade: dist
  
- include_tasks: 
    file: install_kibana.yml
    apply:
      tags: elkinstall,kibana
  tags: elkinstall,kibana
