---
- hosts: elasticsearch 
  become: yes
  remote_user: root
  tasks:
    - import_role:
        name: elasticsearch

# - hosts: kibana 
#   become: yes
#   remote_user: root
#   tasks:
#     - import_role:
#         name: kibana

# - hosts: logstash 
#   become: yes
#   remote_user: root
#   tasks:
#     - import_role:
#         name: logstash

