---
- hosts: elasticsearch 
  become: yes
  remote_user: root
  tasks:
    - import_role:
        name: elasticsearch

#
## Test or install Kibana
#
- hosts: kibana 
  become: yes
  remote_user: root
  tasks:
    - import_role:
        name: kibana

#
## Test or install Logstash
#
- hosts: logstash 
  become: yes
  remote_user: root
  tasks:
    - import_role:
        name: logstash
