global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

scrape_configs:

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.0.101:9100']
    metrics_path: /metrics
