---
- name: Keystore setup | keystore exists
  stat:
    path: "{{ elasticsearch_certs_dir }}/elasticsearch.keystore"
  register: keystore_file

- name: Keystore setup | Copy setup_keystore utils script
  ansible.builtin.template:
    src: setup_keystore.sh.j2
    dest: "{{ elasticsearch_conf_dir }}/setup_keystore.sh"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: u=rwx,g=rwx,o-rwx

- name: Keystore setup | Copy password file
  ansible.builtin.template:
    src: password_file.txt.j2
    dest: /tmp/password_file.txt
    mode: u=rwX,g=rwX,o-rwx
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
  when: not keystore_file.stat.exists

- name: Keystore setup | Create elastic keystore file
  ansible.builtin.command: >
    su - {{ elasticsearch_user }} -c {{ elasticsearch_conf_dir }}/setup_keystore.sh
  when: not keystore_file.stat.exists

- name: Keystore setup | Remove password file
  ansible.builtin.file:
    path: /tmp/password_file.txt
    state: absent
